ADD_SCENE(fliprsdr, start, Start)
ADD_SCENE(fliprsdr, capture, Capture)
ADD_SCENE(fliprsdr, preview, Preview)
ADD_SCENE(fliprsdr, settings, Settings)
ADD_SCENE(fliprsdr, frequency_input, FrequencyInput)
ADD_SCENE(fliprsdr, about, About)
